### ISSUE TITLE
Dead already?

### ISSUE THREAD

**Issue by elmo40** [EpyxZ/APCDCoin#1]
What happened?
No more active nodes?

**Comment by EpyxZ** [comment]
There are 4 active nodes. No nodes have went down.

12:06PM 1/19/2022


12:06:17
￼
getpeerinfo


12:06:17
￼
[
{
"addr" : "185.225.210.103:7777",
"services" : "00000001",
"lastsend" : 1642622690,
"lastrecv" : 1642622693,
"bytessent" : 22179,
"bytesrecv" : 228398,
"conntime" : 1642622689,
"version" : 80023,
"subver" : "/Satoshi:1.0.3/",
"inbound" : false,
"releasetime" : 0,
"startingheight" : 94171,
"banscore" : 0,
"syncnode" : true
},
{
"addr" : "162.220.51.41:7777",
"services" : "00000000",
"lastsend" : 1642622700,
"lastrecv" : 1642622761,
"bytessent" : 124,
"bytesrecv" : 723,
"conntime" : 1642622700,
"version" : 0,
"subver" : "",
"inbound" : false,
"releasetime" : 0,
"startingheight" : -1,
"banscore" : 0
},
{
"addr" : "88.202.187.230:7777",
"services" : "00000000",
"lastsend" : 1642622701,
"lastrecv" : 1642622762,
"bytessent" : 124,
"bytesrecv" : 723,
"conntime" : 1642622701,
"version" : 0,
"subver" : "",
"inbound" : false,
"releasetime" : 0,
"startingheight" : -1,
"banscore" : 0
},
{
"addr" : "31.24.227.249:7777",
"services" : "00000000",
"lastsend" : 1642622747,
"lastrecv" : 1642622762,
"bytessent" : 124,
"bytesrecv" : 530,
"conntime" : 1642622747,
"version" : 0,
"subver" : "",
"inbound" : false,
"releasetime" : 0,
"startingheight" : -1,
"banscore" : 0
}
]

**Comment by EpyxZ** [comment]
Issue is actually NODES disconnecting single client while attempting to download chain. 
Bootstrap created to see if this helps.
